// Autogenerated from Pigeon (v0.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSessionMessage;
@class FLTScreenMessage;
@class FLTConsentsMessage;

@interface FLTSessionMessage : NSObject
@property(nonatomic, copy, nullable) NSString * account;
@property(nonatomic, copy, nullable) NSString * property;
@property(nonatomic, strong, nullable) NSArray * consents;
@end

@interface FLTScreenMessage : NSObject
@property(nonatomic, copy, nullable) NSString * screenName;
@end

@interface FLTConsentsMessage : NSObject
@property(nonatomic, strong, nullable) NSArray * consents;
@end

@protocol FLTDecibelSdkApi
-(void)initialize:(FLTSessionMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setScreen:(FLTScreenMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)uiChanged:(FlutterError *_Nullable *_Nonnull)error;
-(void)setEnableConsents:(FLTConsentsMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setDisableConsents:(FLTConsentsMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTDecibelSdkApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTDecibelSdkApi> _Nullable api);

NS_ASSUME_NONNULL_END
