// Autogenerated from Pigeon (v0.2.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSessionMessage;
@class FLTScreenMessage;
@class FLTConsentsMessage;
@class FLTScreenshotMessage;
@class FLTDimensionStringMessage;
@class FLTDimensionNumberMessage;
@class FLTDimensionBoolMessage;
@class FLTGoalMessage;

@interface FLTSessionMessage : NSObject
@property(nonatomic, copy, nullable) NSString * account;
@property(nonatomic, copy, nullable) NSString * property;
@property(nonatomic, strong, nullable) NSArray * consents;
@end

@interface FLTScreenMessage : NSObject
@property(nonatomic, copy, nullable) NSString * screenName;
@end

@interface FLTConsentsMessage : NSObject
@property(nonatomic, strong, nullable) NSArray * consents;
@end

@interface FLTScreenshotMessage : NSObject
@property(nonatomic, strong, nullable) FlutterStandardTypedData * screenshotData;
@end

@interface FLTDimensionStringMessage : NSObject
@property(nonatomic, copy, nullable) NSString * dimensionName;
@property(nonatomic, copy, nullable) NSString * value;
@end

@interface FLTDimensionNumberMessage : NSObject
@property(nonatomic, copy, nullable) NSString * dimensionName;
@property(nonatomic, strong, nullable) NSNumber * value;
@end

@interface FLTDimensionBoolMessage : NSObject
@property(nonatomic, copy, nullable) NSString * dimensionName;
@property(nonatomic, strong, nullable) NSNumber * value;
@end

@interface FLTGoalMessage : NSObject
@property(nonatomic, copy, nullable) NSString * goal;
@property(nonatomic, strong, nullable) NSNumber * value;
@property(nonatomic, strong, nullable) NSNumber * currency;
@end

@protocol FLTDecibelSdkApi
-(void)initialize:(FLTSessionMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setScreen:(FLTScreenMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setEnableConsents:(FLTConsentsMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setDisableConsents:(FLTConsentsMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)sendScreenshot:(FLTScreenshotMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)sendDimensionWithString:(FLTDimensionStringMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)sendDimensionWithNumber:(FLTDimensionNumberMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)sendDimensionWithBool:(FLTDimensionBoolMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)sendGoal:(FLTGoalMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTDecibelSdkApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTDecibelSdkApi> _Nullable api);

NS_ASSUME_NONNULL_END
