stages:
  - deploy

git_deploy:
  stage: deploy
  before_script:
    - git branch -D master || true
    - git tag | xargs git tag -d || true
  image:
    name: alpine/git
    entrypoint:
      - "/bin/sh"
      - "-c"

  script:
    - git remote add github https://${USER_SDK}:${SECRET_SDK}@github.com/DecibelInsight/decibel-sdk-flutter-binding.git || true
    - git checkout -b master
    - git push -u github master
    - VERSION=$(cat pubspec.yaml | grep "^version:" | awk '{print $2}')
    - git tag ${VERSION}
    - git push -u github --tags
  only:
    - master
