include: package:lint/analysis_options.yaml

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # MedalliaDxa class must contain static methods because it's a plugin
    avoid_classes_with_only_static_members: false


    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    always_declare_return_types: true
    strict-inference: true
    strict-raw-types: true
    prefer_single_quotes: true
    type_annotate_public_apis: true
    unawaited_futures: true
analyzer:
  exclude:
    - lib/messages.dart
