// Autogenerated from Pigeon (v1.0.15), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.decibel.decibel_sdk;

import android.util.Log;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.nio.ByteBuffer;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.HashMap;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression"})
public class Messages {

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class StartScreenMessage {
    private String screenName;
    public String getScreenName() { return screenName; }
    public void setScreenName(String setterArg) { this.screenName = setterArg; }

    private Long screenId;
    public Long getScreenId() { return screenId; }
    public void setScreenId(Long setterArg) { this.screenId = setterArg; }

    private Long startTime;
    public Long getStartTime() { return startTime; }
    public void setStartTime(Long setterArg) { this.startTime = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("screenName", screenName);
      toMapResult.put("screenId", screenId);
      toMapResult.put("startTime", startTime);
      return toMapResult;
    }
    static StartScreenMessage fromMap(Map<String, Object> map) {
      StartScreenMessage fromMapResult = new StartScreenMessage();
      Object screenName = map.get("screenName");
      fromMapResult.screenName = (String)screenName;
      Object screenId = map.get("screenId");
      fromMapResult.screenId = (screenId == null) ? null : ((screenId instanceof Integer) ? (Integer)screenId : (Long)screenId);
      Object startTime = map.get("startTime");
      fromMapResult.startTime = (startTime == null) ? null : ((startTime instanceof Integer) ? (Integer)startTime : (Long)startTime);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class EndScreenMessage {
    private String screenName;
    public String getScreenName() { return screenName; }
    public void setScreenName(String setterArg) { this.screenName = setterArg; }

    private Long screenId;
    public Long getScreenId() { return screenId; }
    public void setScreenId(Long setterArg) { this.screenId = setterArg; }

    private Long endTime;
    public Long getEndTime() { return endTime; }
    public void setEndTime(Long setterArg) { this.endTime = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("screenName", screenName);
      toMapResult.put("screenId", screenId);
      toMapResult.put("endTime", endTime);
      return toMapResult;
    }
    static EndScreenMessage fromMap(Map<String, Object> map) {
      EndScreenMessage fromMapResult = new EndScreenMessage();
      Object screenName = map.get("screenName");
      fromMapResult.screenName = (String)screenName;
      Object screenId = map.get("screenId");
      fromMapResult.screenId = (screenId == null) ? null : ((screenId instanceof Integer) ? (Integer)screenId : (Long)screenId);
      Object endTime = map.get("endTime");
      fromMapResult.endTime = (endTime == null) ? null : ((endTime instanceof Integer) ? (Integer)endTime : (Long)endTime);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class SessionMessage {
    private Long account;
    public Long getAccount() { return account; }
    public void setAccount(Long setterArg) { this.account = setterArg; }

    private Long property;
    public Long getProperty() { return property; }
    public void setProperty(Long setterArg) { this.property = setterArg; }

    private List<Integer> consents;
    public List<Integer> getConsents() { return consents; }
    public void setConsents(List<Integer> setterArg) { this.consents = setterArg; }

    private String version;
    public String getVersion() { return version; }
    public void setVersion(String setterArg) { this.version = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("account", account);
      toMapResult.put("property", property);
      toMapResult.put("consents", consents);
      toMapResult.put("version", version);
      return toMapResult;
    }
    static SessionMessage fromMap(Map<String, Object> map) {
      SessionMessage fromMapResult = new SessionMessage();
      Object account = map.get("account");
      fromMapResult.account = (account == null) ? null : ((account instanceof Integer) ? (Integer)account : (Long)account);
      Object property = map.get("property");
      fromMapResult.property = (property == null) ? null : ((property instanceof Integer) ? (Integer)property : (Long)property);
      Object consents = map.get("consents");
      fromMapResult.consents = (List<Integer>)consents;
      Object version = map.get("version");
      fromMapResult.version = (String)version;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class ConsentsMessage {
    private List<Integer> consents;
    public List<Integer> getConsents() { return consents; }
    public void setConsents(List<Integer> setterArg) { this.consents = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("consents", consents);
      return toMapResult;
    }
    static ConsentsMessage fromMap(Map<String, Object> map) {
      ConsentsMessage fromMapResult = new ConsentsMessage();
      Object consents = map.get("consents");
      fromMapResult.consents = (List<Integer>)consents;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class ScreenshotMessage {
    private byte[] screenshotData;
    public byte[] getScreenshotData() { return screenshotData; }
    public void setScreenshotData(byte[] setterArg) { this.screenshotData = setterArg; }

    private Long screenId;
    public Long getScreenId() { return screenId; }
    public void setScreenId(Long setterArg) { this.screenId = setterArg; }

    private String screenName;
    public String getScreenName() { return screenName; }
    public void setScreenName(String setterArg) { this.screenName = setterArg; }

    private Long startFocusTime;
    public Long getStartFocusTime() { return startFocusTime; }
    public void setStartFocusTime(Long setterArg) { this.startFocusTime = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("screenshotData", screenshotData);
      toMapResult.put("screenId", screenId);
      toMapResult.put("screenName", screenName);
      toMapResult.put("startFocusTime", startFocusTime);
      return toMapResult;
    }
    static ScreenshotMessage fromMap(Map<String, Object> map) {
      ScreenshotMessage fromMapResult = new ScreenshotMessage();
      Object screenshotData = map.get("screenshotData");
      fromMapResult.screenshotData = (byte[])screenshotData;
      Object screenId = map.get("screenId");
      fromMapResult.screenId = (screenId == null) ? null : ((screenId instanceof Integer) ? (Integer)screenId : (Long)screenId);
      Object screenName = map.get("screenName");
      fromMapResult.screenName = (String)screenName;
      Object startFocusTime = map.get("startFocusTime");
      fromMapResult.startFocusTime = (startFocusTime == null) ? null : ((startFocusTime instanceof Integer) ? (Integer)startFocusTime : (Long)startFocusTime);
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class DimensionStringMessage {
    private String dimensionName;
    public String getDimensionName() { return dimensionName; }
    public void setDimensionName(String setterArg) { this.dimensionName = setterArg; }

    private String value;
    public String getValue() { return value; }
    public void setValue(String setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("dimensionName", dimensionName);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static DimensionStringMessage fromMap(Map<String, Object> map) {
      DimensionStringMessage fromMapResult = new DimensionStringMessage();
      Object dimensionName = map.get("dimensionName");
      fromMapResult.dimensionName = (String)dimensionName;
      Object value = map.get("value");
      fromMapResult.value = (String)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class DimensionNumberMessage {
    private String dimensionName;
    public String getDimensionName() { return dimensionName; }
    public void setDimensionName(String setterArg) { this.dimensionName = setterArg; }

    private Double value;
    public Double getValue() { return value; }
    public void setValue(Double setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("dimensionName", dimensionName);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static DimensionNumberMessage fromMap(Map<String, Object> map) {
      DimensionNumberMessage fromMapResult = new DimensionNumberMessage();
      Object dimensionName = map.get("dimensionName");
      fromMapResult.dimensionName = (String)dimensionName;
      Object value = map.get("value");
      fromMapResult.value = (Double)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class DimensionBoolMessage {
    private String dimensionName;
    public String getDimensionName() { return dimensionName; }
    public void setDimensionName(String setterArg) { this.dimensionName = setterArg; }

    private Boolean value;
    public Boolean getValue() { return value; }
    public void setValue(Boolean setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("dimensionName", dimensionName);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static DimensionBoolMessage fromMap(Map<String, Object> map) {
      DimensionBoolMessage fromMapResult = new DimensionBoolMessage();
      Object dimensionName = map.get("dimensionName");
      fromMapResult.dimensionName = (String)dimensionName;
      Object value = map.get("value");
      fromMapResult.value = (Boolean)value;
      return fromMapResult;
    }
  }

  /** Generated class from Pigeon that represents data sent in messages. */
  public static class GoalMessage {
    private String goal;
    public String getGoal() { return goal; }
    public void setGoal(String setterArg) { this.goal = setterArg; }

    private Double value;
    public Double getValue() { return value; }
    public void setValue(Double setterArg) { this.value = setterArg; }

    Map<String, Object> toMap() {
      Map<String, Object> toMapResult = new HashMap<>();
      toMapResult.put("goal", goal);
      toMapResult.put("value", value);
      return toMapResult;
    }
    static GoalMessage fromMap(Map<String, Object> map) {
      GoalMessage fromMapResult = new GoalMessage();
      Object goal = map.get("goal");
      fromMapResult.goal = (String)goal;
      Object value = map.get("value");
      fromMapResult.value = (Double)value;
      return fromMapResult;
    }
  }
  private static class DecibelSdkApiCodec extends StandardMessageCodec {
    public static final DecibelSdkApiCodec INSTANCE = new DecibelSdkApiCodec();
    private DecibelSdkApiCodec() {}
    @Override
    protected Object readValueOfType(byte type, ByteBuffer buffer) {
      switch (type) {
        case (byte)128:         
          return ConsentsMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)129:         
          return DimensionBoolMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)130:         
          return DimensionNumberMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)131:         
          return DimensionStringMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)132:         
          return EndScreenMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)133:         
          return GoalMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)134:         
          return ScreenshotMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)135:         
          return SessionMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        case (byte)136:         
          return StartScreenMessage.fromMap((Map<String, Object>) readValue(buffer));
        
        default:        
          return super.readValueOfType(type, buffer);
        
      }
    }
    @Override
    protected void writeValue(ByteArrayOutputStream stream, Object value)     {
      if (value instanceof ConsentsMessage) {
        stream.write(128);
        writeValue(stream, ((ConsentsMessage) value).toMap());
      } else 
      if (value instanceof DimensionBoolMessage) {
        stream.write(129);
        writeValue(stream, ((DimensionBoolMessage) value).toMap());
      } else 
      if (value instanceof DimensionNumberMessage) {
        stream.write(130);
        writeValue(stream, ((DimensionNumberMessage) value).toMap());
      } else 
      if (value instanceof DimensionStringMessage) {
        stream.write(131);
        writeValue(stream, ((DimensionStringMessage) value).toMap());
      } else 
      if (value instanceof EndScreenMessage) {
        stream.write(132);
        writeValue(stream, ((EndScreenMessage) value).toMap());
      } else 
      if (value instanceof GoalMessage) {
        stream.write(133);
        writeValue(stream, ((GoalMessage) value).toMap());
      } else 
      if (value instanceof ScreenshotMessage) {
        stream.write(134);
        writeValue(stream, ((ScreenshotMessage) value).toMap());
      } else 
      if (value instanceof SessionMessage) {
        stream.write(135);
        writeValue(stream, ((SessionMessage) value).toMap());
      } else 
      if (value instanceof StartScreenMessage) {
        stream.write(136);
        writeValue(stream, ((StartScreenMessage) value).toMap());
      } else 
{
        super.writeValue(stream, value);
      }
    }
  }

  /** Generated interface from Pigeon that represents a handler of messages from Flutter.*/
  public interface DecibelSdkApi {
    void initialize(SessionMessage msg);
    void startScreen(StartScreenMessage msg);
    void endScreen(EndScreenMessage msg);
    void setEnableConsents(ConsentsMessage msg);
    void setDisableConsents(ConsentsMessage msg);
    void saveScreenshot(ScreenshotMessage msg);
    void sendDimensionWithString(DimensionStringMessage msg);
    void sendDimensionWithNumber(DimensionNumberMessage msg);
    void sendDimensionWithBool(DimensionBoolMessage msg);
    void sendGoal(GoalMessage msg);

    /** The codec used by DecibelSdkApi. */
    static MessageCodec<Object> getCodec() {
      return DecibelSdkApiCodec.INSTANCE;
    }

    /** Sets up an instance of `DecibelSdkApi` to handle messages through the `binaryMessenger`. */
    static void setup(BinaryMessenger binaryMessenger, DecibelSdkApi api) {
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.initialize", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              SessionMessage msgArg = (SessionMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.initialize(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.startScreen", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              StartScreenMessage msgArg = (StartScreenMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.startScreen(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.endScreen", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              EndScreenMessage msgArg = (EndScreenMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.endScreen(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.setEnableConsents", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              ConsentsMessage msgArg = (ConsentsMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.setEnableConsents(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.setDisableConsents", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              ConsentsMessage msgArg = (ConsentsMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.setDisableConsents(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.saveScreenshot", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              ScreenshotMessage msgArg = (ScreenshotMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.saveScreenshot(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.sendDimensionWithString", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              DimensionStringMessage msgArg = (DimensionStringMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.sendDimensionWithString(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.sendDimensionWithNumber", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              DimensionNumberMessage msgArg = (DimensionNumberMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.sendDimensionWithNumber(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.sendDimensionWithBool", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              DimensionBoolMessage msgArg = (DimensionBoolMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.sendDimensionWithBool(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(binaryMessenger, "dev.flutter.pigeon.DecibelSdkApi.sendGoal", getCodec());
        if (api != null) {
          channel.setMessageHandler((message, reply) -> {
            Map<String, Object> wrapped = new HashMap<>();
            try {
              ArrayList<Object> args = (ArrayList<Object>)message;
              GoalMessage msgArg = (GoalMessage)args.get(0);
              if (msgArg == null) {
                throw new NullPointerException("msgArg unexpectedly null.");
              }
              api.sendGoal(msgArg);
              wrapped.put("result", null);
            }
            catch (Error | RuntimeException exception) {
              wrapped.put("error", wrapError(exception));
            }
            reply.reply(wrapped);
          });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  private static Map<String, Object> wrapError(Throwable exception) {
    Map<String, Object> errorMap = new HashMap<>();
    errorMap.put("message", exception.toString());
    errorMap.put("code", exception.getClass().getSimpleName());
    errorMap.put("details", "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    return errorMap;
  }
}
